name: Bug report
description: Report a reproducible issue
labels: [bug]
body:
  - type: textarea
    id: summary
    attributes:
      label: Summary
      description: What happened?
      placeholder: Describe the problem and expected behavior.
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: Relevant logs or screenshots
      description: Console/server logs, stack traces, screenshots.
  - type: input
    id: version
    attributes:
      label: Version
      placeholder: v0.1.0 / edge / commit SHA
